web: 
   allowHeaders: 
    - Origin
    - Content-Type
    - Accept
   allowMethods:
   - POST
   - GET
   - OPTIONS
   allowOrigin: '*'
   cacheControl: max-age=600, public
mongodb:
   host: localhost
   username: username
   password: passwsord
   port: 27017
   databaseName: employee-api
   timeout: 15
   ssl: false
s3:
   accessKey:
   secretKey:
   bucketName:
security:
  passwordEncoderSecret: mysecret
  passwordEncoderIteration: 33
  passwordEncoderKeylength: 256
  jjwtSecret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
  jjwtExpiration: 28800
  adminUsername: admin
  adminPassword: admin
  adminEncryptedPassword: dQNjUIMorJb8Ubj2+wVGYp6eAeYkdekqAcnYp+aRq5w=